(()=>{'use strict';
const UNIT_META={
 '01':{title:'ඉංජිනේරු තාක්ෂණවේදය හැඳින්වීම',color:'#22c55e',soft:'#22c55e22',summary:'194 text cards • 26 image cards • 100% note coverage',expected:220},
 '03':{title:'සෞඛ්‍ය හා ආරක්ෂාව',color:'#8b5cf6',soft:'#8b5cf622',summary:'Canonical Unit 03 bank preserved',expected:null},
 '05':{title:'චලිත පරිවර්තන යාන්ත්‍රණය හා ජව සම්ප්‍රේෂණ පද්ධති',color:'#6d55d9',soft:'#6d55d922',summary:'125 cards • 9 sections • 52 image slots',expected:125},
 '06':{title:'ස්වයංචල තාක්ෂණවේදය',color:'#f97316',soft:'#f9731622',summary:'320 text parts • 105 image parts • 60 unique image slots',expected:425}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nl=s=>esc(s).replace(/\n/g,'<br>');
const clamp=(v,min,max,fallback)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):fallback;
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let banks={},unitId='01',studyIndex=0,flipped=false,page=0,db=null,restoreAfterPrint=false;
const STATUS_KEY='etRecallStatusesV3',SIZE_KEY='etRecallCardSizesV3',IMG_EDIT_KEY='etRecallImageEditsV3',TEXT_EDIT_KEY='etRecallTextEditsV4',GLOBAL_KEY='etRecallGlobalPrintV4';
let statuses=readJSON(STATUS_KEY,{}),sizes=readJSON(SIZE_KEY,{}),imageEdits=readJSON(IMG_EDIT_KEY,{}),textEdits=readJSON(TEXT_EDIT_KEY,{}),globalPrint=readJSON(GLOBAL_KEY,{}),images={};
function keyFor(c,id=unitId){return `${id}:${c.baseId||c.id}`}
function statusFor(c){return statuses[keyFor(c)]||''}
function setStatus(c,v){statuses[keyFor(c)]=v;writeJSON(STATUS_KEY,statuses);renderAll()}
function sizeFor(c,side){const v=sizes[keyFor(c)]||{};return clamp(v[side],55,150,100)}
function saveSize(c,side,val){const k=keyFor(c);sizes[k]={...(sizes[k]||{}),[side]:clamp(val,55,150,100)};writeJSON(SIZE_KEY,sizes);renderPrint();renderPairPreview()}
function imgEdit(c){const v=imageEdits[keyFor(c)]||{};return{fit:v.fit||'contain',zoom:clamp(v.zoom,60,180,100),x:clamp(v.x,-60,60,0),y:clamp(v.y,-60,60,0),imgH:clamp(v.imgH,30,96,78),border:v.border!==false}}
function saveImgEdit(c,patch){const k=keyFor(c);imageEdits[k]={...imgEdit(c),...patch};writeJSON(IMG_EDIT_KEY,imageEdits);renderPrint();renderPairPreview()}
function unitGlobal(){return globalPrint[unitId]||{textH:53}}
function globalTextH(){return clamp(unitGlobal().textH,38,53,53)}
function setGlobalTextH(v){globalPrint[unitId]={...unitGlobal(),textH:clamp(v,38,53,53)};writeJSON(GLOBAL_KEY,globalPrint);renderPrint();renderPairPreview();syncTextControls()}
function textEdit(c){const v=textEdits[keyFor(c)]||{};return{h:v.h==null?null:clamp(v.h,38,53,53),qY:clamp(v.qY,-35,35,0),aY:clamp(v.aY,-35,35,0),pad:clamp(v.pad,1,5,2.6),border:v.border!==false}}
function effectiveTextH(c){const v=textEdit(c);return v.h==null?globalTextH():v.h}
function saveTextEdit(c,patch){const k=keyFor(c);textEdits[k]={...textEdit(c),...patch};writeJSON(TEXT_EDIT_KEY,textEdits);renderPrint();renderPairPreview();syncTextControls()}
function cardId(id,i){return `${id}-${String(i+1).padStart(3,'0')}`}
function normalizeCards(id,raw){const list=Array.isArray(raw?.cards)?raw.cards:Array.isArray(raw)?raw:[];return list.map((c,i)=>{if(Array.isArray(c))return{id:cardId(id,i),baseId:cardId(id,i),q:String(c[0]??''),a:String(c[1]??''),section:`Unit ${id}`,image:false,part:1,parts:1};const base=c.baseId||c.id||cardId(id,i);return{id:c.id||base,baseId:base,q:String(c.q??c.question??''),a:String(c.a??c.answer??''),section:c.section||`Unit ${id}`,image:!!c.image,part:Number(c.part||1),parts:Number(c.parts||1)}}).filter(c=>c.q||c.a)}
async function loadLegacy05(){try{const src=await fetch('app.js',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.text()});const s=src.indexOf('const units=');let e=src.indexOf('\n\nconst $=',s);if(e<0)e=src.indexOf('const $=',s);if(s<0||e<0)throw Error('dataset marker not found');const expr=src.slice(s+'const units='.length,e).trim().replace(/;$/,'');const units=Function(`"use strict";return (${expr});`)();const u=units.find(x=>String(x.id)==='05')||units[0];if(u){const cards=normalizeCards('05',u);if(cards.length===125)banks['05']=cards;else console.error('Unit 05 integrity failed',cards.length)}}catch(err){console.error('Unit 05 load failed',err)}}
async function loadOptional(id,path){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)return;const data=await r.json(),cards=normalizeCards(id,data),exp=UNIT_META[id]?.expected;if(exp&&cards.length!==exp){console.error(`Unit ${id} integrity failed`,cards.length,'expected',exp);return}if(cards.length)banks[id]=cards}catch(err){console.error(`Unit ${id} load failed`,err)}}
async function loadUnit01(){try{const names=['unit01-1.json','unit01-2.json','unit01-3.json','unit01-4.json'];const chunks=await Promise.all(names.map(name=>fetch(name,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`${name}: ${r.status}`);return r.json()})));const cards=normalizeCards('01',chunks.flat());const image=cards.filter(c=>c.image).length,text=cards.length-image,sections=new Set(cards.map(c=>c.section)).size;if(cards.length!==220||text!==194||image!==26||sections!==22)throw Error(`Unit 01 integrity failed cards=${cards.length} text=${text} image=${image} sections=${sections}`);banks['01']=cards;window.ET_UNIT01_STATS={cards:220,text:194,image:26,sections:22,source:'Pasted text(7).txt'}}catch(err){console.error('Unit 01 load failed',err)}}
function openDB(){return new Promise(resolve=>{if(!('indexedDB'in window)){resolve(null);return}const req=indexedDB.open('ETRecallImagesV3',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('images'))req.result.createObjectStore('images')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)})}
function dbReadAll(){return new Promise(resolve=>{if(!db){resolve({});return}const tx=db.transaction('images','readonly'),st=tx.objectStore('images'),q=st.getAllKeys();q.onsuccess=()=>{const keys=q.result||[],out={};if(!keys.length){resolve(out);return}let left=keys.length;keys.forEach(k=>{const r=st.get(k);r.onsuccess=()=>{if(r.result)out[k]=r.result;if(--left===0)resolve(out)};r.onerror=()=>{if(--left===0)resolve(out)}})};q.onerror=()=>resolve({})})}
function dbPut(k,v){return new Promise(resolve=>{if(!db){resolve(false);return}const tx=db.transaction('images','readwrite');tx.objectStore('images').put(v,k);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false)})}
function dbDel(k){return new Promise(resolve=>{if(!db){resolve(false);return}const tx=db.transaction('images','readwrite');tx.objectStore('images').delete(k);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false)})}
function compressImage(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{let w=im.naturalWidth,h=im.naturalHeight,s=Math.min(1,1200/w,900/h);w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s));const cv=document.createElement('canvas');cv.width=w;cv.height=h;const cx=cv.getContext('2d');cx.fillStyle='#fff';cx.fillRect(0,0,w,h);cx.drawImage(im,0,0,w,h);resolve(cv.toDataURL('image/jpeg',.84))};im.src=fr.result};fr.readAsDataURL(file)})}
async function uploadImage(c,file){if(!file||!file.type.startsWith('image/'))return;const data=await compressImage(file);images[keyFor(c)]=data;await dbPut(keyFor(c),data);renderImages();renderPrint();renderPairPreview()}
async function removeImage(c){delete images[keyFor(c)];await dbDel(keyFor(c));renderImages();renderPrint();renderPairPreview()}
function currentCards(){return banks[unitId]||[]}
function uniqueImageCards(){const seen=new Set();return currentCards().filter(c=>c.image&&!seen.has(c.baseId)&&seen.add(c.baseId))}
function applyTheme(){const m=UNIT_META[unitId]||UNIT_META['05'];document.documentElement.style.setProperty('--unit',m.color);document.documentElement.style.setProperty('--unit-soft',m.soft)}
function setUnit(id){if(!UNIT_META[id])return;unitId=id;studyIndex=0;flipped=false;page=0;applyTheme();if($('#unitPicker'))$('#unitPicker').value=id;renderAll()}
function unitProgress(id){const cs=banks[id]||[];if(!cs.length)return{done:0,total:0,pct:0,good:0,hard:0};let good=0,hard=0;cs.forEach(c=>{const s=statuses[`${id}:${c.baseId||c.id}`];if(s==='good')good++;if(s==='hard')hard++});return{done:good+hard,total:cs.length,pct:Math.round((good+hard)*100/cs.length),good,hard}}
function renderHero(){const m=UNIT_META[unitId],p=unitProgress(unitId),cs=currentCards();$('#heroTitle').innerHTML='ET <span>Recall</span>';$('#heroSub').textContent=`Unit ${unitId} • ${m.title}`;$('#orb').style.setProperty('--p',p.pct);$('#orbPct').textContent=p.pct+'%';$('#statCards').textContent=cs.length||'—';$('#statGood').textContent=p.good;$('#statHard').textContent=p.hard;$('#statImages').textContent=uniqueImageCards().length;$('#continueBtn').textContent=cs.length?`▶ Unit ${unitId} දිගටම`:`Unit ${unitId} bank sync pending`}
function renderHome(){const root=$('#unitGrid');root.innerHTML=Object.entries(UNIT_META).map(([id,m])=>{const p=unitProgress(id),ready=(banks[id]||[]).length>0;return`<button class="unit-card ${id===unitId?'active':''}" data-unit="${id}"><div class="unit-top"><span class="unit-no">${id}</span><span class="status ${ready?'ready':''}">${ready?`${p.total} READY`:'SYNC PENDING'}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p></button>`}).join('');root.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>setUnit(b.dataset.unit));const p=unitProgress(unitId);$('#todayText').textContent=currentCards().length?`පුළුවන් ${p.good} • බැරි ${p.hard} • තව ${Math.max(0,p.total-p.done)}`:'මෙම unit එකේ card bank එක තව sync වී නැහැ.';$('#todayCount').textContent=Math.max(0,p.total-p.done)}
function renderStudy(){const cs=currentCards(),warning=$('#studyWarning'),stage=$('#focusStage');if(!cs.length){warning.hidden=false;stage.hidden=true;warning.innerHTML=`<b>Unit ${unitId} bank sync pending.</b>`;return}warning.hidden=true;stage.hidden=false;if(studyIndex>=cs.length)studyIndex=0;const c=cs[studyIndex];$('#focusCard').classList.toggle('flipped',flipped);$('#focusQ').textContent=c.q;$('#focusA').textContent=c.a;$('#focusQId').textContent=`UNIT ${unitId} • ${c.id}`;$('#focusAId').textContent=`UNIT ${unitId} • ${c.id}`;$('#studyPos').textContent=`${studyIndex+1} / ${cs.length} • ${statusFor(c)||'new'}`;const img=images[keyFor(c)];$('#focusImage').innerHTML=c.image?(img?`<img src="${img}" alt="${esc(c.baseId)}" style="max-width:100%;max-height:145px;object-fit:contain;background:white;border-radius:10px">`:'🖼️ Image card — image not uploaded'):'';$('#focusImage').style.display=c.image?'grid':'none'}
function nextCard(step=1){const n=currentCards().length;if(!n)return;studyIndex=(studyIndex+step+n)%n;flipped=false;renderStudy()}
function fillSelect(sel,values,first,current){const old=current??sel.value;sel.innerHTML=`<option value="">${first}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(values.includes(old))sel.value=old}
function renderBrowse(){const cs=currentCards(),q=$('#browseSearch').value.trim().toLowerCase(),sec=$('#browseSection').value,st=$('#browseStatus').value,kind=$('#browseKind').value;const sections=[...new Set(cs.map(c=>c.section))];fillSelect($('#browseSection'),sections,'සියලුම කොටස්',sec);const list=cs.filter(c=>(!q||`${c.q} ${c.a} ${c.id}`.toLowerCase().includes(q))&&(!sec||c.section===sec)&&(!st||statusFor(c)===st)&&(!kind||(kind==='image'?c.image:!c.image)));$('#browseCount').textContent=`${list.length} cards`;$('#browseGrid').innerHTML=list.length?list.map(c=>`<article class="browse-card"><div class="badge">UNIT ${unitId} • ${esc(c.id)} • ${esc(c.section)}</div><div class="q">${nl(c.q)}</div><div class="a">${nl(c.a)}</div><div class="card-actions"><button class="btn ghost" data-study="${esc(c.id)}">▶ Study</button><button class="btn ok" data-good="${esc(c.id)}">✓ පුළුවන්</button><button class="btn hard" data-hard="${esc(c.id)}">✕ බැරි</button><button class="btn ghost" data-edit="${esc(c.id)}">⚙ Print edit</button></div></article>`).join(''):`<div class="empty">Cards හමු නොවීය.</div>`;$('#browseGrid').querySelectorAll('[data-study]').forEach(b=>b.onclick=()=>{studyIndex=cs.findIndex(c=>c.id===b.dataset.study);showView('study')});$('#browseGrid').querySelectorAll('[data-good]').forEach(b=>b.onclick=()=>{const c=cs.find(x=>x.id===b.dataset.good);if(c)setStatus(c,'good')});$('#browseGrid').querySelectorAll('[data-hard]').forEach(b=>b.onclick=()=>{const c=cs.find(x=>x.id===b.dataset.hard);if(c)setStatus(c,'hard')});$('#browseGrid').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{showView('print');$('#editCard').value=b.dataset.edit;loadEditControls();renderPairPreview()})}
function renderImages(){const cs=uniqueImageCards(),q=$('#imageSearch').value.trim().toLowerCase(),state=$('#imageState').value,sec=$('#imageSection').value;const sections=[...new Set(cs.map(c=>c.section))];fillSelect($('#imageSection'),sections,'සියලුම Image sections',sec);const list=cs.filter(c=>(!q||`${c.q} ${c.baseId}`.toLowerCase().includes(q))&&(!sec||c.section===sec)&&(!state||(state==='added'?!!images[keyFor(c)]:!images[keyFor(c)])));$('#imageProgress').textContent=`Images: ${cs.filter(c=>images[keyFor(c)]).length} / ${cs.length}`;$('#imageGrid').innerHTML=cs.length?list.map(c=>{const im=images[keyFor(c)];return`<article class="image-card"><div class="badge">UNIT ${unitId} • ${esc(c.baseId)}</div><div class="q">${nl(c.q)}</div><div class="image-preview">${im?`<img src="${im}" alt="${esc(c.baseId)}">`:'IMAGE NOT UPLOADED'}</div><div class="upload"><input type="file" accept="image/*" data-upload="${esc(c.baseId)}"></div><div class="card-actions">${im?`<button class="btn hard" data-remove="${esc(c.baseId)}">Remove</button>`:''}<button class="btn ghost" data-imgedit="${esc(c.baseId)}">Edit print</button></div></article>`}).join(''):`<div class="empty">මෙම unit එකේ image cards නැහැ.</div>`;$('#imageGrid').querySelectorAll('[data-upload]').forEach(inp=>inp.onchange=e=>{const c=cs.find(x=>x.baseId===inp.dataset.upload);if(c)uploadImage(c,e.target.files?.[0])});$('#imageGrid').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const c=cs.find(x=>x.baseId===b.dataset.remove);if(c)removeImage(c)});$('#imageGrid').querySelectorAll('[data-imgedit]').forEach(b=>b.onclick=()=>{showView('print');$('#printSet').value='image';renderPrintControls();$('#editCard').value=b.dataset.imgedit;loadEditControls();renderPrint();renderPairPreview()})}
function printList(){const cs=currentCards(),mode=$('#printSet').value,sec=$('#printSection').value;return cs.filter(c=>(mode==='all'||(mode==='image'?c.image:!c.image))&&(!sec||c.section===sec))}
function printUsesImageMode(){return $('#printSet').value==='image'}
function perPage(){return printUsesImageMode()?6:15}
function mirror(arr){const out=[];for(let i=0;i<arr.length;i+=3)out.push(...arr.slice(i,i+3).reverse());return out}
function initialFont(c,answer){const global=clamp($('#printScale').value,65,135,100)/100,individual=sizeFor(c,answer?'a':'q')/100,base=(answer?4.05:4.25)*global*individual;return Math.max(2.15,base)}
function printCard(c,answer,imageMode=false){const ed=imgEdit(c),te=textEdit(c),img=(!answer&&c.image)?`<div class="pimage" style="height:${ed.imgH}mm;border-style:${ed.border?'dashed':'none'}">${images[keyFor(c)]?`<img src="${images[keyFor(c)]}" alt="${esc(c.baseId)}" style="--fit:${ed.fit};--zoom:${ed.zoom/100};--x:${ed.x}%;--y:${ed.y}%">`:'IMAGE NOT UPLOADED'}</div>`:'';const isText=!c.image&&!imageMode,h=isText?effectiveTextH(c):null,y=isText?(answer?te.aY:te.qY):0;const cardStyle=isText?`height:${h}mm;min-height:${h}mm;max-height:${h}mm;align-self:center;padding:${te.pad}mm;border-style:${te.border?'solid':'none'};`:'';return`<div class="pcard ${answer?'answer':'question'} ${imageMode?'image-mode':''}" data-card="${esc(c.id)}" data-side="${answer?'a':'q'}" style="${cardStyle}">${img}<div class="plabel">${answer?'පිළිතුර':'ප්‍රශ්නය'}</div><div class="ptext" style="--fs:${initialFont(c,answer).toFixed(2)}mm;transform:translateY(${y}%);">${nl(answer?c.a:c.q)}</div><div class="pid">UNIT ${unitId} • ${esc(c.baseId)}${c.parts>1?` • ${c.part}/${c.parts}`:''}</div></div>`}
function sheet(list,p,answer){const pp=perPage(),imageMode=printUsesImageMode();let chunk=list.slice(p*pp,(p+1)*pp);if(answer)chunk=mirror(chunk);return`<section class="a4${imageMode?' image-sheet':''}">${chunk.map(c=>printCard(c,answer,imageMode)).join('')}</section>`}
function ensureAdvancedTextUI(){const box=$('#individualEditor');if(!box||$('#textAdvanced'))return;const el=document.createElement('div');el.id='textAdvanced';el.innerHTML=`<div class="control-title" style="margin-top:12px">Text Card • full controls</div><div class="range-row"><span>Card Height</span><input id="textCardH" type="range" min="38" max="53" step="1" value="53"><output id="textCardHOut">53mm</output></div><div class="range-row"><span>Question Y</span><input id="textQY" type="range" min="-35" max="35" step="1" value="0"><output id="textQYOut">0%</output></div><div class="range-row"><span>Answer Y</span><input id="textAY" type="range" min="-35" max="35" step="1" value="0"><output id="textAYOut">0%</output></div><div class="range-row"><span>Padding</span><input id="textPad" type="range" min="1" max="5" step=".2" value="2.6"><output id="textPadOut">2.6mm</output></div><label class="check-row"><input id="textBorder" type="checkbox" checked> Card border</label><div class="hint">Text cards වෙනම print වේ. Height 53mm max නිසා 15 cards/A4 (3×5) alignment එක ආරක්ෂා වේ. A/B දෙපැත්තට එකම height; Question/Answer Y වෙන වෙනම.</div><button class="btn ghost" id="resetTextEdit" type="button" style="width:100%;margin-top:8px">Reset selected text card</button>`;box.appendChild(el);['textCardH','textQY','textAY','textPad'].forEach(id=>$('#'+id).addEventListener('input',()=>{const c=selectedEditCard();if(!c||c.image)return;saveTextEdit(c,{h:Number($('#textCardH').value),qY:Number($('#textQY').value),aY:Number($('#textAY').value),pad:Number($('#textPad').value),border:$('#textBorder').checked})}));$('#textBorder').addEventListener('change',()=>{const c=selectedEditCard();if(c&&!c.image)saveTextEdit(c,{border:$('#textBorder').checked})});$('#resetTextEdit').onclick=()=>{const c=selectedEditCard();if(!c)return;delete textEdits[keyFor(c)];writeJSON(TEXT_EDIT_KEY,textEdits);syncTextControls();renderPrint();renderPairPreview()}}
function ensureGlobalTextUI(){const host=$('.controls');if(!host||$('#globalTextBox'))return;const anchor=$('#individualEditor');const el=document.createElement('div');el.className='control-group';el.id='globalTextBox';el.innerHTML=`<div class="control-title">Text cards — all cards</div><div class="range-row"><span>Global Height</span><input id="globalTextH" type="range" min="38" max="53" step="1" value="53"><output id="globalTextHOut">53mm</output></div><div class="hint">Selected card එකට custom height දා නැත්නම් මේ height එක භාවිත වේ.</div><button class="btn ghost" id="resetGlobalTextH" type="button" style="width:100%;margin-top:8px">Reset global text height</button>`;host.insertBefore(el,anchor);$('#globalTextH').addEventListener('input',e=>setGlobalTextH(Number(e.target.value)));$('#resetGlobalTextH').onclick=()=>setGlobalTextH(53)}
function syncTextControls(){ensureAdvancedTextUI();ensureGlobalTextUI();if($('#globalTextH')){$('#globalTextH').value=globalTextH();$('#globalTextHOut').textContent=globalTextH()+'mm'}const c=selectedEditCard(),box=$('#textAdvanced');if(!box)return;box.style.display=c&&!c.image?'block':'none';if(!c||c.image)return;const te=textEdit(c),h=effectiveTextH(c);$('#textCardH').value=h;$('#textCardHOut').textContent=h+'mm';$('#textQY').value=te.qY;$('#textQYOut').textContent=te.qY+'%';$('#textAY').value=te.aY;$('#textAYOut').textContent=te.aY+'%';$('#textPad').value=te.pad;$('#textPadOut').textContent=te.pad+'mm';$('#textBorder').checked=te.border}
function renderPrintControls(){ensureAdvancedTextUI();ensureGlobalTextUI();const cs=currentCards(),sections=[...new Set(cs.map(c=>c.section))],oldSec=$('#printSection').value;fillSelect($('#printSection'),sections,'සියලුම කොටස්',oldSec);const cards=printList();const old=$('#editCard').value;$('#editCard').innerHTML=cards.map(c=>`<option value="${esc(c.id)}">${esc(c.id)} — ${esc(c.q.slice(0,48))}</option>`).join('');if(cards.some(c=>c.id===old))$('#editCard').value=old;loadEditControls();syncTextControls()}
function renderPrint(){const list=printList(),pp=perPage(),pages=Math.max(1,Math.ceil(list.length/pp));if(page>=pages)page=pages-1;if(page<0)page=0;const side=$('#printSide').value;$('#preview').innerHTML=!list.length?`<div class="empty" style="width:210mm">No cards in this print set.</div>`:(side==='q'?sheet(list,page,false):side==='a'?sheet(list,page,true):sheet(list,page,false)+sheet(list,page,true));$('#pageLabel').textContent=`Page ${page+1} / ${pages}`;$('#printSummary').innerHTML=`<b>${list.length} cards</b><br>${printUsesImageMode()?'6 cards / A4 • Image cards':'15 cards / A4 • Text cards'}<br>${Math.ceil(list.length/pp)||0} A4 pages`;$('#printScaleOut').textContent=$('#printScale').value+'%';requestAnimationFrame(fitPrintText);renderPairPreview()}
function fitPrintText(){if(!$('#autoFit').checked)return;$$('.ptext').forEach(el=>{let tries=0;while((el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1)&&tries<18){const px=parseFloat(getComputedStyle(el).fontSize);if(px<=8)break;el.style.fontSize=(px*.92)+'px';tries++}})}
function selectedEditCard(){return currentCards().find(c=>c.id===$('#editCard').value)||printList()[0]}
function loadEditControls(){const c=selectedEditCard(),box=$('#individualEditor'),imgBox=$('#imageEditor');if(!c){box.hidden=true;imgBox.hidden=true;return}box.hidden=false;$('#qSize').value=sizeFor(c,'q');$('#aSize').value=sizeFor(c,'a');$('#qSizeOut').textContent=$('#qSize').value+'%';$('#aSizeOut').textContent=$('#aSize').value+'%';imgBox.hidden=!c.image;if(c.image){const ed=imgEdit(c);$('#imgFit').value=ed.fit;$('#imgZoom').value=ed.zoom;$('#imgX').value=ed.x;$('#imgY').value=ed.y;$('#imgH').value=ed.imgH;$('#imgBorder').checked=ed.border;syncImageOutputs()}syncTextControls()}
function syncImageOutputs(){$('#imgZoomOut').textContent=$('#imgZoom').value+'%';$('#imgXOut').textContent=$('#imgX').value+'%';$('#imgYOut').textContent=$('#imgY').value+'%';$('#imgHOut').textContent=$('#imgH').value+'mm'}
function renderPairPreview(){const c=selectedEditCard();if(!c){$('#pairPreview').innerHTML='';return}const mode=c.image;$('#pairPreview').innerHTML=`<div class="live-card"><div class="live-label">A — Question</div>${printCard(c,false,mode)}</div><div class="live-card"><div class="live-label">B — Answer</div>${printCard(c,true,mode)}</div>`;requestAnimationFrame(fitPrintText)}
function renderAllPrint(){const list=printList(),pages=Math.ceil(list.length/perPage()),side=$('#printSide').value;let html='';for(let p=0;p<pages;p++)html+=side==='q'?sheet(list,p,false):side==='a'?sheet(list,p,true):sheet(list,p,false)+sheet(list,p,true);$('#preview').innerHTML=html;requestAnimationFrame(()=>{fitPrintText();setTimeout(()=>window.print(),60)})}
function renderAll(){renderHero();renderHome();renderStudy();renderBrowse();renderImages();renderPrintControls();renderPrint()}
function showView(name){$$('.view').forEach(v=>v.hidden=v.id!==name+'View');$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='study')renderStudy();if(name==='browse')renderBrowse();if(name==='images')renderImages();if(name==='print'){renderPrintControls();renderPrint()}}
function wire(){$$('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#continueBtn').onclick=()=>showView(currentCards().length?'study':'home');$('#unitPicker').onchange=e=>setUnit(e.target.value);$('#flipBtn').onclick=()=>{flipped=!flipped;renderStudy()};$('#focusCard').onclick=e=>{if(!e.target.closest('button')){flipped=!flipped;renderStudy()}};$('#prevStudy').onclick=()=>nextCard(-1);$('#nextStudy').onclick=()=>nextCard(1);$('#goodBtn').onclick=()=>{const c=currentCards()[studyIndex];if(c){setStatus(c,'good');nextCard(1)}};$('#hardBtn').onclick=()=>{const c=currentCards()[studyIndex];if(c){setStatus(c,'hard');nextCard(1)}};['browseSearch','browseSection','browseStatus','browseKind'].forEach(id=>$('#'+id).addEventListener(id==='browseSearch'?'input':'change',renderBrowse));['imageSearch','imageSection','imageState'].forEach(id=>$('#'+id).addEventListener(id==='imageSearch'?'input':'change',renderImages));$('#printSet').onchange=()=>{page=0;renderPrintControls();renderPrint()};$('#printSection').onchange=()=>{page=0;renderPrintControls();renderPrint()};$('#printSide').onchange=renderPrint;$('#printScale').oninput=renderPrint;$('#autoFit').onchange=renderPrint;$('#prevPage').onclick=()=>{page--;renderPrint()};$('#nextPage').onclick=()=>{page++;renderPrint()};$('#editCard').onchange=()=>{loadEditControls();renderPairPreview()};$('#qSize').oninput=()=>{const c=selectedEditCard();$('#qSizeOut').textContent=$('#qSize').value+'%';if(c)saveSize(c,'q',$('#qSize').value)};$('#aSize').oninput=()=>{const c=selectedEditCard();$('#aSizeOut').textContent=$('#aSize').value+'%';if(c)saveSize(c,'a',$('#aSize').value)};$('#resetSizes').onclick=()=>{const c=selectedEditCard();if(!c)return;delete sizes[keyFor(c)];writeJSON(SIZE_KEY,sizes);loadEditControls();renderPrint();renderPairPreview()};['imgFit','imgZoom','imgX','imgY','imgH','imgBorder'].forEach(id=>$('#'+id).addEventListener(id==='imgFit'||id==='imgBorder'?'change':'input',()=>{const c=selectedEditCard();if(!c||!c.image)return;syncImageOutputs();saveImgEdit(c,{fit:$('#imgFit').value,zoom:Number($('#imgZoom').value),x:Number($('#imgX').value),y:Number($('#imgY').value),imgH:Number($('#imgH').value),border:$('#imgBorder').checked})}));$('#resetImageEdit').onclick=()=>{const c=selectedEditCard();if(!c)return;delete imageEdits[keyFor(c)];writeJSON(IMG_EDIT_KEY,imageEdits);loadEditControls();renderPrint();renderPairPreview()};$('#printBtn').onclick=()=>{restoreAfterPrint=true;renderAllPrint()};window.addEventListener('afterprint',()=>{if(restoreAfterPrint){restoreAfterPrint=false;renderPrint()}})}
async function boot(){wire();await Promise.all([loadUnit01(),loadLegacy05(),loadOptional('03','unit03.json'),loadOptional('06','unit06.json')]);db=await openDB();images=await dbReadAll();const qp=new URLSearchParams(location.search).get('unit');if(qp&&banks[qp]?.length)unitId=qp;else if(!banks[unitId]?.length&&banks['01']?.length)unitId='01';applyTheme();$('#unitPicker').value=unitId;renderAll();showView('home')}
boot();
})();